language: c
os: linux
dist:
 - focal
addons:
  apt:
    packages:
      - cppcheck
      - gcovr
script:
  - make clean && make && make cppcheck
  - ./build/RingBuffer
  - gcovr --exclude-unreachable-branches
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
