language: c
sudo: false
addons:
  apt:
    packages:
      - cppcheck
script:
  - make clean && make && make cppcheck
  - ./build/RingBuffer
  - ./gcov.sh
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
